# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Hw06-Readligo-Stephenouu
author: Ligo Scientific Collaboration (LSC) and Stephen Ou
logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "off"

# Information about where the book exists on the web
repository:
  url: https://github.com/UCB-stat-159-s22/hw06-Stephenouu  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
